name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
api-version: 1.13
url: ${url}
commands:
  example:
    aliases: ["ex"]
    description: "This is an example plugin."
